### ISSUE TITLE
Add support for Highlightr plugin

### ISSUE THREAD

**Issue by VincentDuf** [KosmosisDire/obsidian-webpage-export#168]
**Describe the bug**
When I export notes from Obsidian to html format, all the highlighted text only render in yellowish color instead of respecting the color indicated by the tag. As an example `<mark class="hltr-green">text</mark>` won't render in green but in yellow.

Selecting the module in the "Include Plugin CSS" box doesn't change anything.

I'm using Highlightr as another plugin of Obsidian to highlight text. 

**Operating System**
Windows10

**To Reproduce**
1. Install "Highlightr" plugin
2. Highlight a text 
3. Export to html

**Screenshots**
On Obsidian : 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/41116861/de1213bc-223d-4f04-bab6-af76e20e39e7)

After exporting : 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/41116861/5c650704-42f8-45fc-88cd-da8a19f6f64f)

**Comment by VincentDuf** [comment]
Ok I thought it was something like that, thank you for you work btw, I'll wait for your update :)

**Comment by KosmosisDire** [comment]
This should now work in v1.7.0, make sure to select the Highlitr styles in the settings

**Comment by VincentDuf** [comment]
Hi @KosmosisDire,
after update (current version 1.7.3), I still have the issue...
Do you need further materials to work on it ?

Thanks :)

**Comment by u-ways** [comment]
Not working from my side as well. Is there a specific highlight plugin this is intended to work with? (I am on Ubuntu 23 and latest Obsidian)

**Comment by KosmosisDire** [comment]
@VincentDuf 
Hey, I think I have found your problem. Please switch the highlight mode to inline-styles. You will unfortunately have to recreate all the highlights for this to change anything. Let me know if this fixes it. Thanks.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/f98773dc-f2d6-4891-940f-ea8bc53622ce)

**Comment by VincentDuf** [comment]
Hi @KosmosisDire,
thanks for the update and it actually does the trick, so all good for me now.
Cheers !
