### ISSUE TITLE
HTML file only shows part of the note content

### ISSUE THREAD

**Issue by jfkit** [KosmosisDire/obsidian-webpage-export#170]
**Describe the bug**
When I export notes to html, the html file only shows the top part of the note content, and the rest isn't showing at all. 

**Operating System**
Windows 11 Pro

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'More options' Menu of the note
2. Click on 'Export to HTML
3. HTML is generated and web page opens automatically
4. Only some (top portion) of the note's content is displayed (although the headings of the lower sections are included in the TOC on the right).

**Notes**
- If I remove all the headings (replaced with bold formatting), the whole note is shown in the html page.
- I've tried changing any settings that I think might make a difference, such as 'Add filename as title', 'Allow folding headings' & having no H1 headings inline in the note.

**Screenshots**
Screenshot of the Obsidian note
![Screenshot of the note itself](https://github.com/KosmosisDire/obsidian-webpage-export/assets/25111836/874384a0-4abc-4bde-983a-e7d56495d0e8)

Screenshot of the resulting html page
![Screenshot of the html page](https://github.com/KosmosisDire/obsidian-webpage-export/assets/25111836/69a96985-6e9d-40cf-ada1-7ca40f3d63a1)

### IMPORTANT: Error Log
No output in the console.

**Comment by KosmosisDire** [comment]
Thanks for this report, can you try this in a sandbox vault (there is a command to open a sandbox vault). I think this may be caused by some other plugin you have installed.

**Comment by jfkit** [comment]
Thanks for your quick reply.
I thought perhaps it was an issue with another of my plugins or settings, as no-one else seems to have had this issue.
I just did a few tests in the sandbox vault, and compared the results, but unfortunately the content also gets truncated in the sandbox html export.

Example: 

**Screenshot of note content**
<img width="364" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/25111836/c08ac8f7-57f9-47a4-aadb-b0de69fce094">


**Screenshot of html output from my vault**
<img width="418" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/25111836/42002e8b-1949-45ce-86ea-4ee0e7de6d7d">

**Screenshot of html output from sandbox vault**
<img width="421" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/25111836/1d1540e4-edfd-49d0-8a9a-395205aff9d5">

Thanks

**Comment by KosmosisDire** [comment]
Could you send me a copy of the markdown notes that are causing this so I can try to reproduce this? thanks

**Comment by jfkit** [comment]
Sure. 

Any notes will cause the issue, as long as they have headings (I've tried not using H1, only H2+, but the issue is still there).

Even just the Start Here note. I've attached the .md file, but Github won't allow me to attach the .html file.

[Start Here.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/12265921/Start.Here.md)

**Comment by KosmosisDire** [comment]
Hmm I cannot reproduce this if it is consistently caused by any note with headings

**Comment by jfkit** [comment]
Fair enough. I understand.
It's weird because the issue is happening with my personal vault, on my personal desktop PC, using my personal Obsidian account, and also with my work vault, on my work laptop, using my work Obsidian account. Given it's also happening with the sandbox environment, I can't think of anything unique to isolate. I'll keep trying different things when I get the time.

**Comment by ashton2914** [comment]
I have same issue! my obsidian version is v1.4.3 insider preview. 

I have one note without any header but still can not show all content after cover to html, here is some screenshots

![Screenshot 2023-08-19 100026](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17692778/951a9e4f-a2bf-4b94-8af6-a5665b7cb06f)


![Screenshot 2023-08-19 095707](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17692778/22016b75-0f71-4370-8a11-fe958b85af3a)

**Comment by KosmosisDire** [comment]
@ashton2914 Hi! Thank you, can you test this on the current stable version instead of insider?  It may be caused by changes on the insider version that are not present on the stable version

**Comment by ashton2914** [comment]
> @ashton2914 Hi! Thank you, can you test this on the current stable version instead of insider?  It may be caused by changes on the insider version that are not present on the stable version

Thank you for your quick response! I will try it later and feedback.

**Comment by jfkit** [comment]
Thanks Nathan, I'm pretty sure you've narrowed down the cause. 
I just downgraded from the latest insider build to v1.3.7, and tested exporting a couple of times with notes that have multiple headers with different levels
The resulting HTML pages had no issues and displayed all the content of the notes.
Thanks also Ashton. I should have thought to mention that I was using an Insider build.

**Comment by lucacuccu3x8** [comment]
Hi KosmosisDire, is this issue still present in Obsidian v1.4?  Thank you for this amazing plugin btw.

**Comment by KosmosisDire** [comment]
> Hi KosmosisDire, is this issue still present in Obsidian v1.4? Thank you for this amazing plugin btw.

Yes, see this issue: #183 
I am currently working on a fix which will come out soon. Hopefully on monday

**Comment by apertureless** [comment]
Have the same issue with obsidian v1.4

**Comment by KosmosisDire** [comment]
This should be fixed in v1.7.0

**Comment by slaszt** [comment]
I'm still having this issue with v1.8.01 in Obsidian v1.5.8. Granted, I use a lot of plugins and a custom theme. The page I am trying to convert uses the multi-column, dataview, and kanban plugins and I use the Encore theme. I'd appreciate any help with this.

Obsidian vault:

![2024-03-12-215343_1920x1080_scrot](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32940658/364b436c-6d01-4b96-b0f6-c843ad5ba11e)

HTML file in browser (Firefox):

![2024-03-12-215459_1920x1080_scrot](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32940658/cbef38fa-638e-4bba-9d88-ac61a526d73a)

As you can see, additional items in each column are being stripped.

**Comment by KosmosisDire** [comment]
Hi, this is probably a problem with dataview that has been reported before and is fixed in the beta version.

**Comment by slaszt** [comment]
Thank you for the quick reply, but unfortunately updating to the most recent beta didn't seem to help. I did notice that #377 may have something to do with it since I am using the multi-column plugin, so on a hunch I decided to remove the columns to test the output.

This left me with just headings and list items, and still the last line of the document does not show up. I can somewhat force it by adding `<br><br>` to the end of the file, but there are still formatting errors, so I think there must be some kind of parsing issue.

Markdown:

![2024-03-13-102924_1920x1080_scrot](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32940658/ac9cbedb-46b5-46ce-8df6-80411dd2876f)

Notice that the lines are there now, but the last task is still not formatted correctly:

![2024-03-13-103007_1920x1080_scrot](https://github.com/KosmosisDire/obsidian-webpage-export/assets/32940658/23aa59a2-6929-487c-91d1-8615bb36e909)

Debug log, if needed:

```Log:
[INFO] 	Including stylesheet: css-settings-manager
[INFO] 	Including stylesheet: svelte-pcimu8-style
[INFO] 	Including stylesheet: svelte-1vwr9dd-style
[INFO] 	Including stylesheet: svelte-156w7na-style
[INFO] 	Including stylesheet: svelte-q3wqg9-style
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.1-2b
	makeOfflineCompatible     true
	inlineAssets ------------ false
	includePluginCSS          [
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth -----------
	sidebarWidth             
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	relativeOutlineLinks ---- false
	allowFoldingHeadings      true
	allowFoldingLists ------- true
	allowResizingSidebars     false
	logLevel ---------------- all
	minifyHTML                true
	makeNamesWebStyle ------- true
	onlyExportModified        false
	deleteOldFiles ---------- true
	addThemeToggle            true
	addOutline -------------- false
	addFileNav                false
	addSearchBar ------------ false
	addGraphView              false
	addTitle ---------------- true
	addRSSFeed                false
	siteURL ----------------- https://my.site.net/menu/
	authorName               
	vaultTitle -------------- Notes
	exportPreset              website
	openAfterExport --------- false
	graphAttractionForce      1
	graphLinkLength --------- 10
	graphRepulsionForce       150
	graphCentralForce ------- 3
	graphEdgePruning          100
	graphMinNodeSize -------- 3
	graphMaxNodeSize          7
	showDefaultTreeIcons ---- true
	emojiStyle                Native
	defaultFileIcon --------- lucide//file
	defaultFolderIcon         lucide//folder
	defaultMediaIcon -------- lucide//file-image
	exportPath                /srv/menu
	filesToExport ----------- 0
	filePickerBlacklist       [
	filePickerWhitelist ----- [


Enabled Plugins:
	Advanced Tables
	Kanban
	Dataview
	Calendar
	Style Settings
	QuickAdd
	Moviegrabber
	Tasks
	Checklist Reset
	Sheets Extended
	Pandoc Plugin
	Webpage HTML Export
```

I will just wait until the next release since this (obviously) isn't critical, but I thought I would let you know about this behaviour.

**Comment by KosmosisDire** [comment]
Thanks for reporting the problem, I will look into it and see if I am able to reproduce it.
