### ISSUE TITLE
Failed to get render window, export cancelled, in update 1.7.1

### ISSUE THREAD

**Issue by henusys** [KosmosisDire/obsidian-webpage-export#204]
I can't export it correctly, and it show me an error as follows
![1694480835813](https://github.com/KosmosisDire/obsidian-webpage-export/assets/9565297/34e84c5f-d522-4399-8035-6eb79bb8b831)
![1694481499888](https://github.com/KosmosisDire/obsidian-webpage-export/assets/9565297/822238f0-8a4a-4016-8380-1c62415922aa)

obsidian version 1.4.5
windows 10

**Comment by KosmosisDire** [comment]
Does it open a popup window at all? Also this did work in the previous version, correct?

**Comment by henusys** [comment]
Yes it popup a window let me select the export file. But when I choosed a file, export path and click the export button, the error accur with the new popup window as show in issues.

**Comment by KosmosisDire** [comment]
Yes the first popup is expected to work, but is there a second popup that looks like this (or like this but pure white) that pops up for half a second?

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/d0983128-e0f5-4121-84b4-3a6de445c4e9)

Or is it just the noticies in the top corner?

**Comment by henusys** [comment]
Yes, the error notices in the top right corner.

**Comment by KosmosisDire** [comment]
Okay, I will look into this more tomorrow, thanks for the report and sorry it isn't working!

**Comment by myliwenbo** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/29202248/86135fe2-f558-41ac-83df-b7764f5021d9)

Me too.

**Comment by myliwenbo** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/29202248/703c6235-1f9d-4ea4-8aeb-b62e425d0696)
If this mode is selected, CSS is exported but HTML is not included

**Comment by myliwenbo** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/29202248/1e25d91f-14f5-4faf-ba44-a48ed3b677ef)
> If you select this mode nothing will be exported and the following error will be displayed
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/29202248/b884f87f-0d1f-4f03-b742-4887dabb89a3)

**Comment by KosmosisDire** [comment]
question, do you have multiple monitors? And is the popup by any chance opening on a different monitor?

**Comment by henusys** [comment]
Yes, even just using one monitor, it still the same thing. I record a video to show this phenomenon

https://github.com/KosmosisDire/obsidian-webpage-export/assets/9565297/939183bd-ffb4-470e-b652-1cccc0c0f3ff

**Comment by KosmosisDire** [comment]
Thank you, this is very helpful. I am pretty sure I will be able to fix this pretty easily

**Comment by zhoulonghao520** [comment]
V1.7.
 Exporting embedded pages cannot be displayed。
 Exporting embedded  cannot be displayed。

**Comment by dsobkowiakWorkBench** [comment]
OMG! I tested this plugin a few weeks ago and it worked perfectly fine. Now I have this "Failed to get the render window..." error too. Is there a way to get the older version of this plugin. I prepared a "kick of Testing phase" folder for my project in obsidian und wanted to export this part so everybody can access it. 
Is it possible to install the older version of this plugin?

**Comment by KosmosisDire** [comment]
> V1.7. Exporting embedded pages cannot be displayed。 Exporting embedded cannot be displayed。

Hi this is a seperate issue and is a known problem

**Comment by KosmosisDire** [comment]
> @dsobkowiakWorkBench

Yes you can, but be aware that you will not only have to downgrade the plugin but also obsidian itself (which is kinda a task). Part of the reason for this update (and also why so much stuff is broken) is because obsidian changed the way things are rendered in obsidian 1.4+ so unless you downgrade obsidian everything will still not work.

**Comment by KosmosisDire** [comment]
> For me on macOS the options to export dissapeared except for one: ![image](https://user-images.githubusercontent.com/38818455/267295758-39b66002-3889-432d-97e9-5ad5904c5375.png)
> 
> When using export with previous settings, similar thing happens as for the others on windows: <img alt="image" width="804" src="https://user-images.githubusercontent.com/38818455/267295899-aac8a08e-e297-42d2-97ca-7adb725fcebe.png">

@mcaay Hi, this is intentional, however I will add back the old ones soon. For now you can use the right click or more options menu of a given file or folder.

**Comment by dsobkowiakWorkBench** [comment]
@KosmosisDire many thx for your reply. Appreciate you put the effort in this, especially because the plugin is awesome. Ok I will wait till it's fixed and try the feature on my Mac. I tested in on windows so far. I was curious because I downgraded the plugin and the export worked but only half of the stuff was exported. 

regards
Dawid

**Comment by KosmosisDire** [comment]
Hey everyone, this should be fixed in version 1.7.2!

**Comment by bernardb2010** [comment]
Appears to be working now, thanks for the quick update! 🎉

**Comment by mcaay** [comment]
I chose a simple note but it still doesn't export on macOS. Now the popup window is stuck on "Generating HTML".

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/bae5e2cd-982a-4fc3-911e-96a7bb6841a3)

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/d7726e37-83e2-4315-986b-7e5f0312da28)

**Comment by dsobkowiakWorkBench** [comment]
@mcaay you have the actual version of obsidian. 
Mac is working for me now. windows I still have to test

**Comment by mcaay** [comment]
@dsobkowiakWorkBench not sure what you mean. I do have the actual version of Obsidian - should I have some kind of newer beta version? Or an older than current main version?

**Comment by KosmosisDire** [comment]
> I chose a simple note but it still doesn't export on macOS. Now the popup window is stuck on "Generating HTML".
> 
> ![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/bae5e2cd-982a-4fc3-911e-96a7bb6841a3)
> 
> ![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/38818455/d7726e37-83e2-4315-986b-7e5f0312da28)
> 

@mcaay Hi, thanks this is a different issue can you create a new issue and provide more information? Thanks!

**Comment by suradaBANG** [comment]
> Hey everyone, this should be fixed in version 1.7.2! Let me know if this issue persists, if you find a different issue please report it as a new issue

It seems like I have to turn the setting "Include theme toggle" on to fix the problem after your 1.7.2 bugfix. 

Here is the situation:

When I turn off the "Include theme toggle" setting and click "Export as HTML" from the ribbon, then click "export" in the dialog, the html file is generated successfully. However, this file doesn't show anything in the browser. 

Console info is list bellow: 

``` 
//obsidian console log
plugin:webpage-html-export:56581 failed to find render leaf  

// my browser console log
test.html:367  Uncaught (in promise) TypeError: Cannot set properties of null (setting 'checked')
    at e (test.html:367:35201)
    at setupThemeToggle (test.html:367:35964)
    at initializePage (test.html:367:1875)
    at window.onload (test.html:367:3716)
```

I think the "check" vibrable may be related to the "Include theme toggle" setting.

**Comment by KosmosisDire** [comment]
@suradaBANG Hi thanks I am aware of this and it will be fixed in the next release

**Comment by aubreyz** [comment]
Not sure if this is related. I just updated the plugin to 1.7.3 (presumably the next release referred to above) which results in absolutely nothing exporting any longer (worked fine before update). 

Get this in console

![Clipboard-20231008](https://github.com/KosmosisDire/obsidian-webpage-export/assets/25100168/f9a9143d-5fd5-4246-a2c0-137a7b6092f9)

failed to find render leaf

No change other than the plugin update. Obsidian 1.4.14
