### ISSUE TITLE
Dataview plugin exports broken on 1.8.0-8b

### ISSUE THREAD

**Issue by phthallo** [KosmosisDire/obsidian-webpage-export#334]
**Describe the bug**
Anything directly reliant on the Dataview plugin, including standard `dataview` queries and `dataviewjs` does not render correctly on the latest beta release even if included in exported CSS. 

**Operating System**
Windows 10 

**To Reproduce**
1. Use Dataview to render queries
2. Export and ensure that the Dataview plugin is enabled in the 'Include CSS from plugins' section of Asset Options.

**Screenshots**
*Dataview Query for all files in vault*
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/b104cd44-c946-4213-ba0a-38bfc7203bc6)
^ does not show or link to the file, and doesn't show any other columns included in the making of the table (e.g one for tags)
```dataview  
table file.ctime as "Created Time"  
from "/"  
sort file.ctime desc  
```

*Dataview Calendar Query* 
^doesn't render at all
```dataview
calendar file.ctime
```

*DataviewJS Query for all uncompleted tasks in a folder*
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/17a743b9-1ccd-4df9-91e7-1ef593c6fcb8)
^ missing the task text as well as the subheading of the name of the file from which the task originated.
```dataviewjs  
   dv.header(2, 'DataviewJS');  
   dv.taskList(dv.pages('#testfolder').file.tasks  
    .where(t => !t.completed));  
```

### IMPORTANT: Error Log
N/A

p.s: loving the resizable sidebars!

**Comment by KosmosisDire** [comment]
Hmm interesting, I will try and reproduce this and get a fix out today if possible.

**Comment by KosmosisDire** [comment]
Hey, this should be fixed in 1.8.0-9b, could you try it out and let me know. Thanks

**Comment by phthallo** [comment]
Still doesn't seem to be working :') 

If it helps: [here](https://phthallo.github.io/class-notes/index.html) is the main page I use Dataview queries on with my website, and the below image is what it's meant to be appearing as. 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/1990e56e-0075-48b8-9dfd-194d68c4c8a9)

Additionally, there's this Dataview block that's just [stuck on loading](https://phthallo.github.io/class-notes/other/weekly/2024-w05.html), which is meant to look like this:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/c765c2c8-26e6-43ac-b1d9-3d198130de04)

Let me know if you need anything else. 
Thank you so much for your work on this plugin!

**Comment by KosmosisDire** [comment]
Did this work in v1.7.3?

**Comment by KosmosisDire** [comment]
I cannot reproduce this problem at all even with huge dataview queries and multiple queries on the same page. If you just export a single page all by itself that contains one dataview query does that work or does that also break?

**Comment by phthallo** [comment]
1. Yep! Here's what it looks like exported in v1.7.3: 
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/b070b1e1-5d31-476e-8121-ad088fce12d0)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/c9b9d7ef-7b10-4d0e-8019-878e41de7785)

2. That's really interesting, and I have no idea what's causing it. [Here I've uploaded](https://phthallo.github.io/snippets/testing/untitled.html) one of my testing vaults - no plugins installed except for Dataview and Webpage Export v1.8.0-9b, and the theme is Obsidian's default one. 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/84078890/d47cccbb-891c-409c-ba6b-d7f5c5b4f053)
This image is what it looks like in the vault, but it's showing the Loading... on the export. 
Debug info for the testing vault: https://pastebin.com/abYEuebH

**Comment by KosmosisDire** [comment]
Hmmm I have no idea what is happening. Dataview queries really should work. I'll do what I can, but since I can't reproduce it I will just kinda be guessing at what is wrong. Could you give me the specs of the computer you are using? I am thinking it might actually be some sort of race condition which is caused by a faster or slower computer than mine.

**Comment by phthallo** [comment]
(if this entire thing was caused by a computer skill issue that'd be kinda funny 💀)
It's a Lenovo Yoga C740 with 8GB RAM and an Intel Core i5-10210U 10th Gen processor.

**Comment by KosmosisDire** [comment]
Hey, can you verify this is fixed in the beta version 1.8.0-10b?

**Comment by phthallo** [comment]
Yep, it's fixed! Thanks so much, this plugin is awesome :)

**Comment by KosmosisDire** [comment]
So glad that is working for you now, and I am glad you are enjoying the plugin! :)
