### ISSUE TITLE
Add option for adding content at the start/end of every webpage.

### ISSUE THREAD

**Issue by WinnerWind** [KosmosisDire/obsidian-webpage-export#533]
**Is your feature request related to a problem? Please describe.**
I like to link a page on my website that takes the viewer to the Contact page where they can contact me for further queries or corrections.
![image](https://github.com/user-attachments/assets/cda539c0-5d1a-4e83-83ce-fe14de732426)
This needs to be manually added to every single file, which takes up space and makes it hard to edit down the line (Eg. I move where the contact's page is down the line)

**Describe the solution you'd like**
An option to add a header template and a footer template file as defined by the user, which automatically appends the contents of those files to the start/end of every page/defined pages

**Describe alternatives you've considered**
Copy pasting each and every note
using templates
Using tags to quickly find the place where this contact's footer is found
frontmatter

**Additional context**
There exists an option to use Head content for the plugin, especially with regards to my use case, but I am not sure how to use it for this purpose. It seems perfect, but I am not sure how to use it. A guide would be helpful.

**Comment by KosmosisDire** [comment]
Yes this should be acomplished using the head content. I will create a tutorial for document modifications eventually. But basically you can just upload a javascript file that would add the element dynamically to each page when it loads. You can explore the available frontend api by opening the dev tools on your exported site and typing in `ObsidianSite.` and exploruing the different objects and options available to interact with.

**Comment by WinnerWind** [comment]
Hi there. It seems my email didn't go through.

I'm looking forward to that tutorial. I looked around in ObsidianSite. but couldn't find anything that was relevant to my needs. Could you point me to the most relevant function?

**Comment by WinnerWind** [comment]
Hi there! I'm sorry for bumping this. 
I've looked through all the functions of `ObsidianSite` and I just cannot figure out which function I should use/which object I should modify to do what I need to. My best guesses are `ObsidianSite.document` (Not sure how I can modify that...) `ObsidianSite.loadWebsiteData()` (not sure how it works either....)

Anyway, I'm looking forward to that tutorial!

**Comment by KosmosisDire** [comment]
Hi sorry I forgot to get back on this. It is pretty simple, you should be able to run something like this:
```js
ObsidianSite.onDocumentLoad((doc) => 
{
    var footer = document.createElement("div");
    footer.innerText = "Hello World!";
    doc.footerEl.appendChild(footer);
});
```
`ObsidianSite.onDocumentLoad` allows you to run a function which returnsany document when it is loaded and allows modifications to the document. Adding elements to the footerEl is probably what you want. This API will get better in the upcoming release as I have put a lot of focus on modularity. Let me know if this doesn't work or if you need any other help :)

**Comment by WinnerWind** [comment]
Hi there!
I'm not super experienced with HTML or Java, but here's what I did : 

I have a folder in my vault that contains various stuff my site could need, like favicons and such called `! - DO NOT EXPORT`. Here I put the `head.html` file I made.
![image](https://github.com/user-attachments/assets/0b748578-9cb8-4b45-b1ac-b475a44b306e)

In custom head content I put the following settings
![image](https://github.com/user-attachments/assets/d500df0d-7995-4bb6-9a63-8cc17bfb7857)
The path points to 
`! - DO NOT EXPORT/head.html`

`head.html` contains
```html
<!DOCTYPE html>
<html>
<head>
    <title>Obsidian Page with Footer</title>
    <script>
        ObsidianSite.onDocumentLoad((doc) => {
            var footer = document.createElement("div");
            footer.innerText = "Hello World!";
            doc.footerEl.appendChild(footer);
        });
    </script>
</head>
<body>
    </body>
</html>
```
I wasn't sure what to look for, so I did a search on the website in the inspector and that returned nothing
![image](https://github.com/user-attachments/assets/b914746c-236c-4bd4-a34e-f2966f736d85)
And it doesn't appear anywhere on the site either
![image](https://github.com/user-attachments/assets/532e41ca-0cf7-4ac1-b70e-cc6eb30c9fb1)

Note : I did purge +  delete and re-exported everything

**Comment by KosmosisDire** [comment]
Thanks, can you try just pasting the script into the dev tools console in the browser and then switch to a new page and see if it works there? Also what version of the plugin are you using?

**Comment by WinnerWind** [comment]
![image](https://github.com/user-attachments/assets/31156619-faf6-4d0d-88cd-97a0bbc129fd)
Hi!
that worked!
Not sure why I didn't try that at first...
Now I think it has to do with the path itself.
I'm on the following version
![image](https://github.com/user-attachments/assets/175876ba-7765-44dc-a6f7-12875a4210f8)

**Comment by KosmosisDire** [comment]
Ironically I think that custom head content may be broken in this version. Let me actually go ahead and release a new beta right now, just for you lmao

If you could install the new beta version from BRAT let me know how that goes :)

**Comment by WinnerWind** [comment]
Hi there! No rush, custom Head content is more of a novelty for my site, not a necessity.
No need to develop anything *just for* me, considering there are a lot more critical issues needed to be fixed. Let me know when the update is done though! I'll be sure to update via BRAT and let you know

**Comment by KosmosisDire** [comment]
It is actually already done, I already had it fixed in the dev branch just hadn't released it yet XD

**Comment by WinnerWind** [comment]
Hi! I put the exact same path as before
`! - DO NOT EXPORT/head.html` but it still doesn't do anythig.
Does HTMLExport look for a full path (i.e. `/home/user/Documents/...`) or is it with reference to the vault itself? Also, do I need to put escape characters for spaces?

**Comment by WinnerWind** [comment]
Unfortunately, the browse button does not work properly, so I have to type it myself. It's probably a quirk of my desktop environment because some other apps behave like this too. I decided to type in the whole path, which is `/home/soham/Documents/Diary/Vaults/My Site/! - DO NOT EXPORT/head.html`
Now, the *entire head.html* file is just
```html
<script>
    ObsidianSite.onDocumentLoad((doc) => {
        var footer = document.createElement("div");
        footer.innerText = "Hello World!";
        doc.footerEl.appendChild(footer);
    });
</script>
```
and I re-opened obsidian, and lo and behold, it worked!
![image](https://github.com/user-attachments/assets/d8954fa2-c34d-4cda-924f-f0080481fc93)
Thank you for helping me out with this, and i'll be sure to let you know if this feature breaks in future versions. I'll also have to experiment on making this more dynamic (eg. headings and such, but it should be easy now that we got it working).
I'll keep this issue open in case. Feel free to close it if you believe it's truly done.

**Comment by WinnerWind** [comment]
A question :
How do I do headings, and links (hrefs and such) from this state? I tried
```html
<script>
    ObsidianSite.onDocumentLoad((doc) => {
        var footer = document.createElement("div");
        footer.innerText = "<h1>END OF FILE</h1>";
        doc.footerEl.appendChild(footer);
    });
</script>
``` and it wouldn't render the footer in a heading. I even tried `# END OF FILE` but that too did nothing 
![image](https://github.com/user-attachments/assets/b46624c5-f0d7-4542-b512-66a766be935f)

**Comment by KosmosisDire** [comment]
Yeah, if you do want to write plain html inside a div like that, you can use innerHTML rather than innerText. But I think you've got it :)

**Comment by WinnerWind** [comment]
I did, but still, thanks for the tip on `innerHTML`! There were more options just by inspecting all the properties of `document.createElement("div")`, all of them seem extremely useful 
![image](https://github.com/user-attachments/assets/4501c426-bd2b-48f5-bf07-f39e5666c97a)
