### ISSUE TITLE
Unable to export the rendering result of the dataview.

### ISSUE THREAD

**Issue by tyf2018** [KosmosisDire/obsidian-webpage-export#73]
**Describe the bug**
Unable to export the rendering result of the dataview, resulting in a blank export or an export with only an empty table.

**Operating System**
windows 10 
obsidian 1.2.6

**To Reproduce**
Normal export operation.

**Screenshots**
![image](https://user-images.githubusercontent.com/56342788/235331917-217465b7-c1f6-4f88-832b-9325ad656ba3.png)

### IMPORTANT: Error Log
[obsidian.md-1682820068484.log](https://github.com/KosmosisDire/obsidian-webpage-export/files/11360436/obsidian.md-1682820068484.log)

**Comment by KosmosisDire** [comment]
Hey, I am unable to reproduce this, is there any way you could supply the markdown that causes this error or provide instructions for how to reproduce the error in the simplest way, other than just exporting dataview?

**Comment by tyf2018** [comment]
> provide instructions for how to reproduce the error in the simplest way

This is the dataview code I am using. 
[dataviewJS-test.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/11361145/dataviewJS-test.md)

This is the exported result with empty content.
[dataviewJS-test.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11361146/dataviewJS-test.zip)

Best regards.

**Comment by KosmosisDire** [comment]
Thank you, for now it is very likely that you can fix this by turning off the background renderer in the settings.

**Comment by KosmosisDire** [comment]
I am going to replace the background exporter with a different method which will be slightly slower but will have all the same features as the old exporter, but it should be more stable and allow you to keep using obsidian while it exports. Once that comes out this should be fixed.

**Comment by KosmosisDire** [comment]
This should be fixed in version 1.5.1. Thanks for the report!

**Comment by tyf2018** [comment]
Thank you for your prompt response and update. However, I am still encountering issues when exporting. I have two note libraries, and the issues vary depending on the number of notes.
1. Library with a small number of notes (approximately 500 notes): Generally, it can be exported normally, but when encountering complex dataview codes, the export will still result in a blank output without errors report. The compressed file below contains the dataview code, exported HTML file, and console log. 
[dataviewJS-test2023-05-02.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/11368800/dataviewJS-test2023-05-02.zip)

2. The other library is relatively larger, with over 11,000 notes. When exporting, an error message occurs immediately. 
![image](https://user-images.githubusercontent.com/56342788/235554657-92545b67-427d-4403-8479-ec597b6faddb.png)

Best regards.

**Comment by KosmosisDire** [comment]
Interesting, I will look into this right away. If you could could you just copy this into a new issue? Thanks!
